### ISSUE TITLE
Incorrect highlighting of unclosed ` in comment

### ISSUE THREAD

**Issue by zhxnlai** [textmate/swift.tmbundle#11]
I first found this problem [here](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift)

To reproduce:
~~~swift
/**
`Array` or `Dictionary, 
*/
let x =  1
~~~

**Comment by infininight** [comment]
Corrected, thanks!

Submitted a [pull request](https://github.com/github/linguist/pull/2048) to have it corrected on Github as well.
