### ISSUE TITLE
Complex sequences break highlighting

### ISSUE THREAD

**Issue by idrougge** [textmate/swift.tmbundle#28]
Some Swift sequences cause the syntax highlighter to quit its job. I can't tell ifit is caused by chains of closures or uncommon sequences of double quotes. This can be observed at the end of https://github.com/idrougge/advent_of_code_2016/blob/master/idrougge-swift/day5/md5.swift where the text turns a uniform blue in the last portion of the code. It seems to be triggered by this line:
```c.h.forEach{hh+=String(format:"%08X\($0.distanceTo(c.h.last!)==0 ? "":" ")",$0.bigEndian)}```

**Comment by jtbandes** [comment]
Should be fixed along with #25 already.
